[package]
name = "markdown-editor-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
pulldown-cmark = "0.9.3"
clipboard = "0.5.0"